modLoader="javafml"
loaderVersion="[26,)"
license="GGPL3"
issueTrackerURL="https://github.com/Lance5057/Butchercraft/issues"
[[mods]]
modId="butchercraft"
version="${file.jarVersion}"
displayName="Butchercraft"
displayURL="https://github.com/Lance5057/Butchercraft"
credits="Alan199921, DivineAspect, Skysom, FreneticScribbler, Lanse505, Belathus, RoyalJelly"
authors="Lance5057"